//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city_dropdown
    {
        public int city_id { get; set; }
        public string city_name { get; set; }
    
        public virtual state_dropdown state_dropdown { get; set; }
    }
}
