//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_log
    {
        public int LogID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual customer_details customer_details { get; set; }
    }
}
