//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_master
    {
        public int login_id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> role_id { get; set; }
        public List<role_master> Roles { get; set; }
    }
}
