//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_table
    {
        public source_table()
        {
            this.destination_table = new HashSet<destination_table>();
        }
    
        public int source_id { get; set; }
        public string source_type { get; set; }
    
        public virtual ICollection<destination_table> destination_table { get; set; }
    }
}
