//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_details
    {
        public long TxnId { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TxnType { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
    }
}
